---
services:
  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379

  mongo:
    image: mongo:6.0.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
